### PR TITLE
Add support of proxy_logs option

### PR DESCRIPTION
**Pull request by dionys**
This patch added support of proxy_logs parameter that was implemented in Ubic 1.48_01.

### CODE REVIEW

**Comment by throughnothing** [comment]
Cleaning out old Pull requests, please re-open if you'd still like to see this get in, and I'd be happy to look

**Comment by dionys** [comment]
I still like to get this feature. But I can't reopen this PR.

**Comment by throughnothing** [comment]
I pushed this to CPAN at version `0.003`.  Thanks for the patch, sorry for the delay!

**Comment by dionys** [comment]
Thanks.

**Pull request merged**
